Add "High Resolution" mode for OSX
TigerVNC/tigervnc pull request #1206
Opened 2021-02-13 15:53 UTC by junhaoliao

#878 

This commit fixes the HiDPI incompatibility of vncviewer on OSX. 

Now the sizes of the render images are multiplied by the backingScaleFactor and can be displayed normally on the screen: https://developer.apple.com/documentation/appkit/nsscreen/1388385-backingscalefactor?language=objc

### Before:
![image](https://user-images.githubusercontent.com/43196707/107854126-e2825f80-6de7-11eb-8edb-47d25b08f532.png)

### After:
![image](https://user-images.githubusercontent.com/43196707/107854129-eada9a80-6de7-11eb-9d67-a3f212a083a6.png)

### Known Issues:
The vncviewer viewport sizes are not committed to the server at launch, and the control still mismatches with the image in the beginning. The user will need to either specify "-Maximize" in the arguments, or manually resize the viewer after launching the viewer. This issue is no longer observed when I compile the viewer with FLTK 1.4.0:
https://www.fltk.org/doc-1.4/drawing.html#ssect_DrawingUnit:~:text=DPI%2Dindependent

(Sorry this is my first time submitting a pull request. It will be great if you can point out anything inappropriate. Thanks in advance!)

2021-03-01 13:52 UTC, CendioOssman requested changes
The issues you mentioned will also need to be resolved before we can merge this.

Have you done any performance profiling? Last time we had to back this out because it was slower than standard DPI mode.

2021-03-01 13:52 UTC, CendioOssman commented on vncviewer/Surface_OSX.cxx
> +  const double scale_factor = cocoa_get_scale_factor();
Shouldn't this just be for when rendering to the screen? Not another Surface?

And I think it also depends on FLTK version. Perhaps we need to look at the transformation matrix?

2021-05-17 14:20 UTC, prasskaly commented
Hi, 
This is probably something I would like to try out. Is there a beta binary available with this update?

2021-06-08 14:51 UTC, CendioOssman commented
No response. Closing.

2021-06-08 14:51 UTC, closed without merging