Build fixes to libvnc.so for Xorg-server-21.1.1
TigerVNC/tigervnc pull request #1383
Opened 2021-11-24 19:08 UTC by joakim-tjernlund

This makes libvnc Xorg module against Xorg-server-21.1.1.
Note that now one must enable present support in Xorg to make
libvnc build.

Only build tested though.

2021-11-26 09:09 UTC, CendioOssman requested changes
Thanks. Most of this looks fine. But I think it's safer to clone of the patch file, just like we've done previously. Avoids issues in case we need to do further tweaks in the future for 21.

PS. I thought 21 required Meson?

2021-11-26 10:18 UTC, joakim-tjernlund commented
> Thanks. Most of this looks fine. But I think it's safer to clone of the patch file, just like we've done previously. Avoids issues in case we need to do further tweaks in the future for 21.

Done.
> 
> PS. I thought 21 required Meson?

I think they just added meson but the old autotools system is still there.

2021-11-26 10:57 UTC, merged

2021-11-26 13:49 UTC, joakim-tjernlund commented
Just remembered, the patching miinitext.c look odd, is that really needed?
If not one could just build libvnc against an already installed Xorg and remove the patching competently.
Then tigervnc does not have to bother with meson later on either.

2021-11-29 08:13 UTC, CendioOssman commented
That's so that Xvnc is built correctly, so I'm afraid it is needed. We also use internal APIs, so we will always need to be built in the Xorg source tree.

2021-11-29 10:05 UTC, joakim-tjernlund commented
> That's so that Xvnc is built correctly, so I'm afraid it is needed. We also use internal APIs, so we will always need to be built in the Xorg source tree.

I see, does that extend to the libvnc.so Xorg module as well?

2021-11-29 10:27 UTC, CendioOssman commented
Yup. That's why it needs to be rebuilt when Xorg changes. I think the only somewhat stable API is the graphics driver API, and we need more than that.